apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: frontend-applicationset
spec:
  generators:
    - list:
        elements:
          - environment: dev
            cluster: https://kubernetes.default.svc
          - environment: prod
            cluster: https://kubernetes.default.svc
  template:
    metadata:
      name: 'frontend-{{environment}}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/your-repo'
        path: 'charts/frontend'
        targetRevision: HEAD
        helm:
          parameters:
            - name: "image.tag"
              value: "latest"
      destination:
        server: '{{cluster}}'
        namespace: '{{environment}}'

---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: backend-applicationset
spec:
  generators:
    - list:
        elements:
          - environment: dev
            cluster: https://kubernetes.default.svc
          - environment: prod
            cluster: https://kubernetes.default.svc
  template:
    metadata:
      name: 'backend-{{environment}}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/your-repo'
        path: 'charts/backend'
        targetRevision: HEAD
        helm:
          parameters:
            - name: "image.tag"
              value: "latest"
      destination:
        server: '{{cluster}}'
        namespace: '{{environment}}'
