apiVersion: v1
kind: Service
metadata:
  name: specific-service-name  # Custom name for the service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: {{ include "chartname.labels" . | default .Release.Name }}